name: Update Exchange Rates

on:
  schedule:
    - cron: '0 7 20 * *'  # Runs at 07:00 UTC on the 20th of each month
  workflow_dispatch:       # Allow manual trigger in Actions tab

permissions:
  contents: write          # Required to allow git push

jobs:
  update-exchange-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Enables push using GITHUB_TOKEN

      - name: Make script executable
        run: chmod +x ./download_and_publish.sh

      - name: Run exchange rate updater
        run: ./download_and_publish.sh
